### ISSUE TITLE
Feedback (UI) #1

### ISSUE THREAD

**Issue by faultables** [evilfactorylabs/alchemy#3]
Halo gan @chorzkie, thank you for the PR. I've some ~~feedback~~ proposal regarding the design. First of all, the UI looks like this on my screen:

![Screen Shot 2020-04-06 at 9 26 22 AM](https://user-images.githubusercontent.com/6561394/78517839-b4f08100-77e8-11ea-8030-e42affccbe79.png)

Which is great but probably looks much wider on desktop. Here is the design with additional outline:

![Screen Shot 2020-04-06 at 9 27 20 AM](https://user-images.githubusercontent.com/6561394/78517876-d6516d00-77e8-11ea-9d16-01354817aa28.png)

Probably we need to make a container more narrow? Here is my proposal design

![Screen Shot 2020-04-06 at 9 41 22 AM](https://user-images.githubusercontent.com/6561394/78518527-e9fdd300-77ea-11ea-96b8-943383467508.png)

with additional background color (#f4f4f4) to the body and some box shadow (0, 4px, 8px, rgba(0, 0, 0, 0.1)) to distinguish the card.

what do you think? And sorry for not making the design earlier

**Comment by chorzkie** [comment]
Boljug gan, oke ntar ane sesuaikan. Terlalu lebar emang kurang gaya sih ya haha

**Comment by faultables** [comment]
tar langsung buat PR aja gan, ini saya lanjut yg backendnya duluu
